"use client";

import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import Eye from "@mui/icons-material/VisibilityRounded";
import LockKeyhole from "@mui/icons-material/LockRounded";
import Plus from "@mui/icons-material/AddRounded";
import RefreshCw from "@mui/icons-material/RefreshRounded";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { createPayrollPeriodAction, generatePayrollAction, lockPayrollPeriodAction, previewPayrollAction, type PayrollPreviewRow } from "@/features/payroll/actions";
import { payrollPeriodSchema, type PayrollPeriodValues } from "@/features/payroll/schemas/payroll-schema";

type PeriodRow = { id: string; name: string; startDate: string; endDate: string; status: string; totalAmount: number; employeeCount: number; deductions: PayrollPreviewRow[] };
const today = new Date().toISOString().slice(0, 10);

export function PayrollManager({ periods }: { periods: PeriodRow[] }) {
  const [createOpen, setCreateOpen] = useState(false); const [previewOpen, setPreviewOpen] = useState(false); const [previewRows, setPreviewRows] = useState<PayrollPreviewRow[]>([]); const [previewName, setPreviewName] = useState(""); const [loading, setLoading] = useState(false);
  const form = useForm<PayrollPeriodValues>({ resolver: zodResolver(payrollPeriodSchema), defaultValues: { name: "", startDate: today, endDate: today } });
  async function create(values: PayrollPeriodValues) { const result = await createPayrollPeriodAction(values); if (!result.ok) return toast.error(result.error); toast.success("Payroll period created."); setCreateOpen(false); form.reset({ name: "", startDate: today, endDate: today }); }
  async function preview(id: string) { setLoading(true); const result = await previewPayrollAction(id); setLoading(false); if (!result.ok || !("rows" in result)) return toast.error(result.error); setPreviewRows(result.rows); setPreviewName(result.period.name); setPreviewOpen(true); }
  async function generate(id: string) { setLoading(true); const result = await generatePayrollAction(id); setLoading(false); if (!result.ok) return toast.error(result.error); toast.success(`${result.count} deduction summaries generated.`); }
  async function lock(id: string) { const result = await lockPayrollPeriodAction(id); if (!result.ok) return toast.error(result.error); toast.success("Payroll period locked."); }
  function details(period: PeriodRow) { setPreviewRows(period.deductions); setPreviewName(period.name); setPreviewOpen(true); }
  return <><div className="flex justify-end"><Button onClick={() => setCreateOpen(true)}><Plus data-icon="inline-start" />Create period</Button></div><div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Period</TableHead><TableHead>Dates</TableHead><TableHead>Status</TableHead><TableHead>Employees</TableHead><TableHead>Total deductions</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{periods.length ? periods.map((period) => <TableRow key={period.id}><TableCell className="font-medium">{period.name}</TableCell><TableCell className="font-mono text-xs">{period.startDate} to {period.endDate}</TableCell><TableCell><Badge variant={period.status === "LOCKED" ? "secondary" : "outline"}>{period.status}</Badge></TableCell><TableCell>{period.employeeCount}</TableCell><TableCell className="font-mono">₱{period.totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</TableCell><TableCell><div className="flex gap-1"><Button size="icon-sm" variant="ghost" aria-label="Preview deductions" onClick={() => preview(period.id)} disabled={loading}><Eye /></Button>{period.status !== "LOCKED" ? <Button size="icon-sm" variant="ghost" aria-label="Generate deductions" onClick={() => generate(period.id)} disabled={loading}><RefreshCw /></Button> : null}{period.status === "GENERATED" ? <Button size="icon-sm" variant="ghost" aria-label="Lock payroll period" onClick={() => lock(period.id)}><LockKeyhole /></Button> : null}{period.deductions.length ? <Button size="sm" variant="outline" onClick={() => details(period)}>Details</Button> : null}</div></TableCell></TableRow>) : <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No payroll periods found.</TableCell></TableRow>}</TableBody></Table></div>
  <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Create payroll period</DialogTitle><DialogDescription>Payroll date ranges cannot overlap existing periods.</DialogDescription></DialogHeader><form onSubmit={form.handleSubmit(create)} className="flex flex-col gap-4"><FieldGroup><Field><FieldLabel>Name</FieldLabel><Input {...form.register("name")} /></Field><Field><FieldLabel>Start date</FieldLabel><Input type="date" {...form.register("startDate")} /></Field><Field><FieldLabel>End date</FieldLabel><Input type="date" {...form.register("endDate")} /></Field></FieldGroup><FieldError>{Object.values(form.formState.errors)[0]?.message}</FieldError><DialogFooter><Button type="button" variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button><Button type="submit">Create period</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={previewOpen} onOpenChange={setPreviewOpen}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-5xl"><DialogHeader><DialogTitle>{previewName} deductions</DialogTitle><DialogDescription>Employee summaries with attendance and unpaid-leave breakdowns.</DialogDescription></DialogHeader><div className="flex flex-col gap-4">{previewRows.length ? previewRows.map((row) => <div key={row.employeeId} className="rounded-xl border"><div className="grid gap-3 p-4 md:grid-cols-4"><div><p className="font-medium">{row.employee}</p><p className="text-xs text-muted-foreground">Salary ₱{row.monthlySalary.toFixed(2)}</p></div><Metric label="Daily rate" value={`₱${row.dailyRate.toFixed(2)}`} /><Metric label="Penalty / LWOP units" value={row.dayValue.toFixed(3)} /><Metric label="Deduction" value={`₱${row.amount.toFixed(2)}`} /></div><div className="overflow-x-auto border-t"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Source</TableHead><TableHead>Late</TableHead><TableHead>Undertime</TableHead><TableHead>Absence</TableHead><TableHead>LWOP</TableHead><TableHead>Penalty / LWOP units</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{row.breakdowns.map((item) => <TableRow key={item.date}><TableCell className="font-mono">{item.date}</TableCell><TableCell>{item.source.replaceAll("_", " ")}</TableCell><TableCell>{item.lateMinutes ?? 0}</TableCell><TableCell>{item.undertimeMinutes ?? 0}</TableCell><TableCell>{item.absenceDayValue ?? 0}</TableCell><TableCell>{item.lwopDayValue ?? 0}</TableCell><TableCell>{item.dayValue.toFixed(3)}</TableCell><TableCell>₱{item.amount.toFixed(2)}</TableCell></TableRow>)}</TableBody></Table></div></div>) : <p className="rounded-lg bg-muted p-6 text-center text-muted-foreground">No deductions for this period.</p>}</div></DialogContent></Dialog></>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-mono font-medium">{value}</p></div>; }
