"use client";

import { useState } from "react";
import { Check, X } from "lucide-react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { decideOverloadAction, decideOvertimeAction, generateOverloadAction, generateOvertimeAction } from "@/features/overtime-overload/actions";

type OvertimeRow = { id: string; employee: string; department: string; date: string; minutes: number; hours: number; status: string; remarks: string };
type OverloadRow = { id: string; employee: string; department: string; weekStart: string; weekEnd: string; totalTeachingHours: number; regularLoadHours: number; overloadHours: number; status: string; remarks: string };
const today = new Date().toISOString().slice(0, 10);

export function OvertimeOverloadManager({ overtime, overload }: { overtime: OvertimeRow[]; overload: OverloadRow[] }) {
  const [from, setFrom] = useState(today); const [to, setTo] = useState(today); const [week, setWeek] = useState(today); const [loading, setLoading] = useState(false);
  async function generateOvertime() { setLoading(true); const result = await generateOvertimeAction(from, to); setLoading(false); if (!result.ok) return toast.error(result.error); toast.success(`${result.count} overtime record(s) generated.`); }
  async function generateOverload() { setLoading(true); const result = await generateOverloadAction(week); setLoading(false); if (!result.ok || !("weekStart" in result)) return toast.error(result.error); toast.success(`${result.count} overload record(s) generated for week ${result.weekStart}.`); }
  async function decide(kind: "overtime" | "overload", id: string, status: "APPROVED" | "REJECTED") { const result = kind === "overtime" ? await decideOvertimeAction(id, status) : await decideOverloadAction(id, status); if (!result.ok) return toast.error(result.error); toast.success(`${kind === "overtime" ? "Overtime" : "Overload"} ${status.toLowerCase()}.`); }
  const pendingOvertime = overtime.filter((row) => row.status === "PENDING").length; const approvedHours = overtime.filter((row) => row.status === "APPROVED").reduce((sum, row) => sum + row.hours, 0); const pendingOverload = overload.filter((row) => row.status === "PENDING").length; const approvedOverload = overload.filter((row) => row.status === "APPROVED").reduce((sum, row) => sum + row.overloadHours, 0);
  return <div className="flex flex-col gap-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Summary title="Pending overtime" value={String(pendingOvertime)} /><Summary title="Approved OT hours" value={approvedHours.toFixed(3)} /><Summary title="Pending overload" value={String(pendingOverload)} /><Summary title="Approved overload hours" value={approvedOverload.toFixed(3)} /></div><Tabs defaultValue="overtime"><TabsList><TabsTrigger value="overtime">Staff Overtime</TabsTrigger><TabsTrigger value="overload">Faculty Overload</TabsTrigger></TabsList><TabsContent value="overtime" className="mt-4 flex flex-col gap-4"><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-card p-4"><Field><FieldLabel>From</FieldLabel><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></Field><Field><FieldLabel>To</FieldLabel><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></Field><Button onClick={generateOvertime} disabled={loading}>Generate overtime</Button></div><RecordTable headers={["Date", "Employee", "Minutes", "Hours", "Status", "Remarks", "Actions"]} empty="No overtime records found.">{overtime.map((row) => <TableRow key={row.id}><TableCell className="font-mono">{row.date}</TableCell><EmployeeCell name={row.employee} department={row.department} /><TableCell>{row.minutes}</TableCell><TableCell className="font-mono">{row.hours.toFixed(3)}</TableCell><Status value={row.status} /><TableCell>{row.remarks || "—"}</TableCell><DecisionButtons pending={row.status === "PENDING"} onApprove={() => decide("overtime", row.id, "APPROVED")} onReject={() => decide("overtime", row.id, "REJECTED")} /></TableRow>)}</RecordTable></TabsContent><TabsContent value="overload" className="mt-4 flex flex-col gap-4"><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-card p-4"><Field><FieldLabel>Week containing</FieldLabel><Input type="date" value={week} onChange={(event) => setWeek(event.target.value)} /></Field><Button onClick={generateOverload} disabled={loading}>Generate weekly overload</Button></div><RecordTable headers={["Week", "Employee", "Teaching", "Regular load", "Overload", "Status", "Remarks", "Actions"]} empty="No overload records found.">{overload.map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.weekStart}<br />{row.weekEnd}</TableCell><EmployeeCell name={row.employee} department={row.department} /><TableCell className="font-mono">{row.totalTeachingHours.toFixed(3)}</TableCell><TableCell className="font-mono">{row.regularLoadHours.toFixed(3)}</TableCell><TableCell className="font-mono">{row.overloadHours.toFixed(3)}</TableCell><Status value={row.status} /><TableCell>{row.remarks || "—"}</TableCell><DecisionButtons pending={row.status === "PENDING"} onApprove={() => decide("overload", row.id, "APPROVED")} onReject={() => decide("overload", row.id, "REJECTED")} /></TableRow>)}</RecordTable></TabsContent></Tabs></div>;
}

function Summary({ title, value }: { title: string; value: string }) { return <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><p className="font-mono text-2xl font-semibold">{value}</p></CardContent></Card>; }
function RecordTable({ headers, empty, children }: { headers: string[]; empty: string; children: React.ReactNode }) { const hasRows = Array.isArray(children) ? children.length > 0 : Boolean(children); return <div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow>{headers.map((header) => <TableHead key={header}>{header}</TableHead>)}</TableRow></TableHeader><TableBody>{hasRows ? children : <TableRow><TableCell colSpan={headers.length} className="h-24 text-center text-muted-foreground">{empty}</TableCell></TableRow>}</TableBody></Table></div>; }
function EmployeeCell({ name, department }: { name: string; department: string }) { return <TableCell><p className="font-medium">{name}</p><p className="text-xs text-muted-foreground">{department}</p></TableCell>; }
function Status({ value }: { value: string }) { return <TableCell><Badge variant={value === "APPROVED" ? "secondary" : "outline"}>{value}</Badge></TableCell>; }
function DecisionButtons({ pending, onApprove, onReject }: { pending: boolean; onApprove: () => void; onReject: () => void }) { return <TableCell>{pending ? <div className="flex gap-1"><Button size="icon-sm" variant="ghost" aria-label="Approve" onClick={onApprove}><Check /></Button><Button size="icon-sm" variant="ghost" aria-label="Reject" onClick={onReject}><X /></Button></div> : "—"}</TableCell>; }
