import AccessTimeFilledRoundedIcon from "@mui/icons-material/AccessTimeFilledRounded";
import EventAvailableRoundedIcon from "@mui/icons-material/EventAvailableRounded";
import GroupsRoundedIcon from "@mui/icons-material/GroupsRounded";
import PaymentsRoundedIcon from "@mui/icons-material/PaymentsRounded";
import { Badge } from "@/components/ui/badge";
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AttendanceChart } from "@/features/dashboard/components/attendance-chart";
import { PayrollDeductionsTable, type DeductionRow } from "@/features/dashboard/components/payroll-deductions-table";

type DashboardData = { totalEmployees: number; facultyCount: number; staffCount: number; presentToday: number; attendanceRate: number; pendingLeave: number; deductionTotal: number; periodLabel: string; leaveStatuses: Array<{ label: string; value: number; variant: "secondary" | "outline" | "destructive" }>; trend: Array<{ day: string; present: number; absent: number }>; deductions: DeductionRow[]; today: string };
export function DashboardOverview({ data }: { data: DashboardData }) {
  const metrics = [
    { label: "Total employees", value: String(data.totalEmployees), detail: `${data.facultyCount} faculty · ${data.staffCount} staff`, icon: GroupsRoundedIcon },
    { label: "Present today", value: String(data.presentToday), detail: `${data.attendanceRate}% attendance rate`, icon: EventAvailableRoundedIcon },
    { label: "Pending leave", value: String(data.pendingLeave), detail: "Applications awaiting review", icon: AccessTimeFilledRoundedIcon },
    { label: "Current deductions", value: `₱${data.deductionTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, detail: "Recorded attendance deductions", icon: PaymentsRoundedIcon },
  ];
  return <section className="flex flex-col gap-6"><div className="flex flex-col justify-between gap-4 border-b pb-5 md:flex-row md:items-end"><div><h2 className="text-2xl font-bold tracking-[-0.025em] md:text-[1.75rem]">Institutional overview</h2><p className="mt-1.5 text-sm text-muted-foreground">Live workforce activity for {data.today}.</p></div><Badge variant="outline">{data.periodLabel}</Badge></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const Icon = metric.icon; return <Card key={metric.label}><CardHeader><CardDescription className="font-medium">{metric.label}</CardDescription><CardAction><div className="flex size-11 items-center justify-center rounded-lg bg-secondary text-primary"><Icon aria-hidden="true" fontSize="small" /></div></CardAction><CardTitle className="text-2xl font-bold tracking-tight">{metric.value}</CardTitle></CardHeader><CardContent><p className="text-xs text-muted-foreground">{metric.detail}</p></CardContent></Card>; })}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,0.75fr)]"><Card><CardHeader><CardTitle>Attendance trend</CardTitle><CardDescription>Present and absent records over the last five days.</CardDescription></CardHeader><CardContent><AttendanceChart data={data.trend} /></CardContent></Card><Card><CardHeader><CardTitle>Leave status</CardTitle><CardDescription>Applications currently in the database.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5">{data.leaveStatuses.map((status) => <div key={status.label} className="flex items-center justify-between border-b pb-4 last:border-b-0 last:pb-0"><p className="text-sm font-medium">{status.label}</p><Badge variant={status.variant}>{status.value}</Badge></div>)}</CardContent></Card></div><Card><CardHeader><CardTitle>Recent attendance deductions</CardTitle><CardDescription>Latest computed deductions from encoded attendance.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><PayrollDeductionsTable records={data.deductions} /></CardContent></Card></section>;
}
